package at.bitfire.nophonespam

data class CountryCode(
    val flag: String,
    val name: String,
    val dialCode: String
) {
    override fun toString(): String =
        if (dialCode.isEmpty()) name
        else "$flag $name (+$dialCode)"

    companion object {
        /**
         * Find the best-matching country code for a phone number.
         * Tries longest dial codes first so e.g. "+1684" matches American Samoa before "+1" matches US.
         * Returns the index into COUNTRIES, or 0 (None) if no match found.
         */
        fun findByDialCode(number: String?): Int {
            if (number == null || !number.startsWith("+")) return 0
            val digits = number.substring(1)
            val sortedIndices = COUNTRIES.indices.sortedByDescending { COUNTRIES[it].dialCode.length }
            for (idx in sortedIndices) {
                val code = COUNTRIES[idx].dialCode
                if (code.isNotEmpty() && digits.startsWith(code)) return idx
            }
            return 0
        }

        /**
         * Given a full number and a matched country index, return the local part
         * (the number with the country dial code prefix stripped).
         */
        fun stripDialCode(number: String?, countryIndex: Int): String {
            if (countryIndex <= 0 || number == null) return number ?: ""
            val code = "+${COUNTRIES[countryIndex].dialCode}"
            return if (number.startsWith(code)) number.substring(code.length) else number
        }

        val COUNTRIES: Array<CountryCode> = arrayOf(
            CountryCode("", "None", ""),
            CountryCode("🇦🇫", "Afghanistan", "93"),
            CountryCode("🇦🇱", "Albania", "355"),
            CountryCode("🇩🇿", "Algeria", "213"),
            CountryCode("🇦🇸", "American Samoa", "1684"),
            CountryCode("🇦🇩", "Andorra", "376"),
            CountryCode("🇦🇴", "Angola", "244"),
            CountryCode("🇦🇮", "Anguilla", "1264"),
            CountryCode("🇦🇬", "Antigua and Barbuda", "1268"),
            CountryCode("🇦🇷", "Argentina", "54"),
            CountryCode("🇦🇲", "Armenia", "374"),
            CountryCode("🇦🇼", "Aruba", "297"),
            CountryCode("🇦🇺", "Australia", "61"),
            CountryCode("🇦🇹", "Austria", "43"),
            CountryCode("🇦🇿", "Azerbaijan", "994"),
            CountryCode("🇧🇸", "Bahamas", "1242"),
            CountryCode("🇧🇭", "Bahrain", "973"),
            CountryCode("🇧🇩", "Bangladesh", "880"),
            CountryCode("🇧🇧", "Barbados", "1246"),
            CountryCode("🇧🇾", "Belarus", "375"),
            CountryCode("🇧🇪", "Belgium", "32"),
            CountryCode("🇧🇿", "Belize", "501"),
            CountryCode("🇧🇯", "Benin", "229"),
            CountryCode("🇧🇲", "Bermuda", "1441"),
            CountryCode("🇧🇹", "Bhutan", "975"),
            CountryCode("🇧🇴", "Bolivia", "591"),
            CountryCode("🇧🇦", "Bosnia and Herzegovina", "387"),
            CountryCode("🇧🇼", "Botswana", "267"),
            CountryCode("🇧🇷", "Brazil", "55"),
            CountryCode("🇧🇳", "Brunei", "673"),
            CountryCode("🇧🇬", "Bulgaria", "359"),
            CountryCode("🇧🇫", "Burkina Faso", "226"),
            CountryCode("🇧🇮", "Burundi", "257"),
            CountryCode("🇰🇭", "Cambodia", "855"),
            CountryCode("🇨🇲", "Cameroon", "237"),
            CountryCode("🇨🇦", "Canada", "1"),
            CountryCode("🇨🇻", "Cape Verde", "238"),
            CountryCode("🇰🇾", "Cayman Islands", "1345"),
            CountryCode("🇨🇫", "Central African Republic", "236"),
            CountryCode("🇹🇩", "Chad", "235"),
            CountryCode("🇨🇱", "Chile", "56"),
            CountryCode("🇨🇳", "China", "86"),
            CountryCode("🇨🇴", "Colombia", "57"),
            CountryCode("🇰🇲", "Comoros", "269"),
            CountryCode("🇨🇩", "Congo (DRC)", "243"),
            CountryCode("🇨🇬", "Congo (Republic)", "242"),
            CountryCode("🇨🇰", "Cook Islands", "682"),
            CountryCode("🇨🇷", "Costa Rica", "506"),
            CountryCode("🇨🇮", "Côte d'Ivoire", "225"),
            CountryCode("🇭🇷", "Croatia", "385"),
            CountryCode("🇨🇺", "Cuba", "53"),
            CountryCode("🇨🇾", "Cyprus", "357"),
            CountryCode("🇨🇿", "Czech Republic", "420"),
            CountryCode("🇩🇰", "Denmark", "45"),
            CountryCode("🇩🇯", "Djibouti", "253"),
            CountryCode("🇩🇲", "Dominica", "1767"),
            CountryCode("🇩🇴", "Dominican Republic", "1809"),
            CountryCode("🇪🇨", "Ecuador", "593"),
            CountryCode("🇪🇬", "Egypt", "20"),
            CountryCode("🇸🇻", "El Salvador", "503"),
            CountryCode("🇬🇶", "Equatorial Guinea", "240"),
            CountryCode("🇪🇷", "Eritrea", "291"),
            CountryCode("🇪🇪", "Estonia", "372"),
            CountryCode("🇪🇹", "Ethiopia", "251"),
            CountryCode("🇫🇰", "Falkland Islands", "500"),
            CountryCode("🇫🇴", "Faroe Islands", "298"),
            CountryCode("🇫🇯", "Fiji", "679"),
            CountryCode("🇫🇮", "Finland", "358"),
            CountryCode("🇫🇷", "France", "33"),
            CountryCode("🇬🇫", "French Guiana", "594"),
            CountryCode("🇵🇫", "French Polynesia", "689"),
            CountryCode("🇬🇦", "Gabon", "241"),
            CountryCode("🇬🇲", "Gambia", "220"),
            CountryCode("🇬🇪", "Georgia", "995"),
            CountryCode("🇩🇪", "Germany", "49"),
            CountryCode("🇬🇭", "Ghana", "233"),
            CountryCode("🇬🇮", "Gibraltar", "350"),
            CountryCode("🇬🇷", "Greece", "30"),
            CountryCode("🇬🇱", "Greenland", "299"),
            CountryCode("🇬🇩", "Grenada", "1473"),
            CountryCode("🇬🇵", "Guadeloupe", "590"),
            CountryCode("🇬🇺", "Guam", "1671"),
            CountryCode("🇬🇹", "Guatemala", "502"),
            CountryCode("🇬🇳", "Guinea", "224"),
            CountryCode("🇬🇼", "Guinea-Bissau", "245"),
            CountryCode("🇬🇾", "Guyana", "592"),
            CountryCode("🇭🇹", "Haiti", "509"),
            CountryCode("🇭🇳", "Honduras", "504"),
            CountryCode("🇭🇰", "Hong Kong", "852"),
            CountryCode("🇭🇺", "Hungary", "36"),
            CountryCode("🇮🇸", "Iceland", "354"),
            CountryCode("🇮🇳", "India", "91"),
            CountryCode("🇮🇩", "Indonesia", "62"),
            CountryCode("🇮🇷", "Iran", "98"),
            CountryCode("🇮🇶", "Iraq", "964"),
            CountryCode("🇮🇪", "Ireland", "353"),
            CountryCode("🇮🇱", "Israel", "972"),
            CountryCode("🇮🇹", "Italy", "39"),
            CountryCode("🇯🇲", "Jamaica", "1876"),
            CountryCode("🇯🇵", "Japan", "81"),
            CountryCode("🇯🇴", "Jordan", "962"),
            CountryCode("🇰🇿", "Kazakhstan", "7"),
            CountryCode("🇰🇪", "Kenya", "254"),
            CountryCode("🇰🇮", "Kiribati", "686"),
            CountryCode("🇰🇵", "North Korea", "850"),
            CountryCode("🇰🇷", "South Korea", "82"),
            CountryCode("🇰🇼", "Kuwait", "965"),
            CountryCode("🇰🇬", "Kyrgyzstan", "996"),
            CountryCode("🇱🇦", "Laos", "856"),
            CountryCode("🇱🇻", "Latvia", "371"),
            CountryCode("🇱🇧", "Lebanon", "961"),
            CountryCode("🇱🇸", "Lesotho", "266"),
            CountryCode("🇱🇷", "Liberia", "231"),
            CountryCode("🇱🇾", "Libya", "218"),
            CountryCode("🇱🇮", "Liechtenstein", "423"),
            CountryCode("🇱🇹", "Lithuania", "370"),
            CountryCode("🇱🇺", "Luxembourg", "352"),
            CountryCode("🇲🇴", "Macau", "853"),
            CountryCode("🇲🇰", "Macedonia", "389"),
            CountryCode("🇲🇬", "Madagascar", "261"),
            CountryCode("🇲🇼", "Malawi", "265"),
            CountryCode("🇲🇾", "Malaysia", "60"),
            CountryCode("🇲🇻", "Maldives", "960"),
            CountryCode("🇲🇱", "Mali", "223"),
            CountryCode("🇲🇹", "Malta", "356"),
            CountryCode("🇲🇭", "Marshall Islands", "692"),
            CountryCode("🇲🇶", "Martinique", "596"),
            CountryCode("🇲🇷", "Mauritania", "222"),
            CountryCode("🇲🇺", "Mauritius", "230"),
            CountryCode("🇲🇽", "Mexico", "52"),
            CountryCode("🇫🇲", "Micronesia", "691"),
            CountryCode("🇲🇩", "Moldova", "373"),
            CountryCode("🇲🇨", "Monaco", "377"),
            CountryCode("🇲🇳", "Mongolia", "976"),
            CountryCode("🇲🇪", "Montenegro", "382"),
            CountryCode("🇲🇸", "Montserrat", "1664"),
            CountryCode("🇲🇦", "Morocco", "212"),
            CountryCode("🇲🇿", "Mozambique", "258"),
            CountryCode("🇲🇲", "Myanmar", "95"),
            CountryCode("🇳🇦", "Namibia", "264"),
            CountryCode("🇳🇷", "Nauru", "674"),
            CountryCode("🇳🇵", "Nepal", "977"),
            CountryCode("🇳🇱", "Netherlands", "31"),
            CountryCode("🇳🇨", "New Caledonia", "687"),
            CountryCode("🇳🇿", "New Zealand", "64"),
            CountryCode("🇳🇮", "Nicaragua", "505"),
            CountryCode("🇳🇪", "Niger", "227"),
            CountryCode("🇳🇬", "Nigeria", "234"),
            CountryCode("🇳🇺", "Niue", "683"),
            CountryCode("🇳🇴", "Norway", "47"),
            CountryCode("🇴🇲", "Oman", "968"),
            CountryCode("🇵🇰", "Pakistan", "92"),
            CountryCode("🇵🇼", "Palau", "680"),
            CountryCode("🇵🇸", "Palestine", "970"),
            CountryCode("🇵🇦", "Panama", "507"),
            CountryCode("🇵🇬", "Papua New Guinea", "675"),
            CountryCode("🇵🇾", "Paraguay", "595"),
            CountryCode("🇵🇪", "Peru", "51"),
            CountryCode("🇵🇭", "Philippines", "63"),
            CountryCode("🇵🇱", "Poland", "48"),
            CountryCode("🇵🇹", "Portugal", "351"),
            CountryCode("🇵🇷", "Puerto Rico", "1787"),
            CountryCode("🇶🇦", "Qatar", "974"),
            CountryCode("🇷🇪", "Réunion", "262"),
            CountryCode("🇷🇴", "Romania", "40"),
            CountryCode("🇷🇺", "Russia", "7"),
            CountryCode("🇷🇼", "Rwanda", "250"),
            CountryCode("🇰🇳", "Saint Kitts and Nevis", "1869"),
            CountryCode("🇱🇨", "Saint Lucia", "1758"),
            CountryCode("🇻🇨", "Saint Vincent and the Grenadines", "1784"),
            CountryCode("🇼🇸", "Samoa", "685"),
            CountryCode("🇸🇲", "San Marino", "378"),
            CountryCode("🇸🇹", "São Tomé and Príncipe", "239"),
            CountryCode("🇸🇦", "Saudi Arabia", "966"),
            CountryCode("🇸🇳", "Senegal", "221"),
            CountryCode("🇷🇸", "Serbia", "381"),
            CountryCode("🇸🇨", "Seychelles", "248"),
            CountryCode("🇸🇱", "Sierra Leone", "232"),
            CountryCode("🇸🇬", "Singapore", "65"),
            CountryCode("🇸🇰", "Slovakia", "421"),
            CountryCode("🇸🇮", "Slovenia", "386"),
            CountryCode("🇸🇧", "Solomon Islands", "677"),
            CountryCode("🇸🇴", "Somalia", "252"),
            CountryCode("🇿🇦", "South Africa", "27"),
            CountryCode("🇸🇸", "South Sudan", "211"),
            CountryCode("🇪🇸", "Spain", "34"),
            CountryCode("🇱🇰", "Sri Lanka", "94"),
            CountryCode("🇸🇩", "Sudan", "249"),
            CountryCode("🇸🇷", "Suriname", "597"),
            CountryCode("🇸🇿", "Swaziland", "268"),
            CountryCode("🇸🇪", "Sweden", "46"),
            CountryCode("🇨🇭", "Switzerland", "41"),
            CountryCode("🇸🇾", "Syria", "963"),
            CountryCode("🇹🇼", "Taiwan", "886"),
            CountryCode("🇹🇯", "Tajikistan", "992"),
            CountryCode("🇹🇿", "Tanzania", "255"),
            CountryCode("🇹🇭", "Thailand", "66"),
            CountryCode("🇹🇱", "Timor-Leste", "670"),
            CountryCode("🇹🇬", "Togo", "228"),
            CountryCode("🇹🇰", "Tokelau", "690"),
            CountryCode("🇹🇴", "Tonga", "676"),
            CountryCode("🇹🇹", "Trinidad and Tobago", "1868"),
            CountryCode("🇹🇳", "Tunisia", "216"),
            CountryCode("🇹🇷", "Turkey", "90"),
            CountryCode("🇹🇲", "Turkmenistan", "993"),
            CountryCode("🇹🇨", "Turks and Caicos Islands", "1649"),
            CountryCode("🇹🇻", "Tuvalu", "688"),
            CountryCode("🇺🇬", "Uganda", "256"),
            CountryCode("🇺🇦", "Ukraine", "380"),
            CountryCode("🇦🇪", "United Arab Emirates", "971"),
            CountryCode("🇬🇧", "United Kingdom", "44"),
            CountryCode("🇺🇸", "United States", "1"),
            CountryCode("🇺🇾", "Uruguay", "598"),
            CountryCode("🇺🇿", "Uzbekistan", "998"),
            CountryCode("🇻🇺", "Vanuatu", "678"),
            CountryCode("🇻🇦", "Vatican City", "379"),
            CountryCode("🇻🇪", "Venezuela", "58"),
            CountryCode("🇻🇳", "Vietnam", "84"),
            CountryCode("🇻🇬", "British Virgin Islands", "1284"),
            CountryCode("🇻🇮", "U.S. Virgin Islands", "1340"),
            CountryCode("🇼🇫", "Wallis and Futuna", "681"),
            CountryCode("🇾🇪", "Yemen", "967"),
            CountryCode("🇿🇲", "Zambia", "260"),
            CountryCode("🇿🇼", "Zimbabwe", "263")
        )
    }
}
